import React from "react";
import "./gardenease.css"
import gardeneaseHome from "../assets/gardenease-home.png";
import gardeneaseHomeMobile from "../assets/gardenease-home-mobile.png";


function GardenEase() {
  return (
    <div className="gardenease-project">
      <div className="gardenease-presentation">
        <h1>GardenEase</h1>
        <p className="ge-text">GardenEase is a website for people who would like
          to start gardening at their place, but don't know how to start.<br/>
          By understanding your preferences and home environment, GardenEase
          provides tailored gardening projects with step-by-step care advices.<br/>
          GardenEase was built during the 2 last weeks of the bootcamp. We were a group of 3 students.
        </p>
        <h4 className="ge-parts">How does it work ?</h4>
        <p className="ge-text">GardenEase asks you to define some criterias regarding
          the place your live, to be able to generate gardening projects that will be
          working at your place and location: do you live in a shady flat ? Do you plan to
          put the plant in a humid part of the house ? Do you expect flours ? Cooking herbs ? etc.<br/>
          A promt with your answers is sent to ChatGPT. It will then generate a strctured answer
          that will then be restructured in the HTML. 
        </p>
        <a className="ge-desktop" href="http://www.gardenease.io" target="_blank" rel="noreferrer"><img className="gardenease-home" src={gardeneaseHome} alt="gardenease"></img></a>
        <a className="ge-mobile" href="http://www.gardenease.io" target="_blank" rel="noreferrer"><img className="gardenease-home-mobile" src={gardeneaseHomeMobile} alt="gardenease"></img></a>
      </div>
      <div className="ge-details">
        <h2>My contributions</h2>
        <p className="ge-text">During these 2 weeks working on GardenEase, I had the oportunity to work
          as well on the frontend and on the backend.
        </p>
        <h4 className="ge-parts">Home page / About page:</h4>
        <p className="ge-text">Mainly frontend (not the plant animation)</p>
        <h4 className="ge-parts">Loading page:</h4>
        <p className="ge-text">Frontend and backend</p>
        <h4 className="ge-parts">Project show page:</h4>
        <p className="ge-text">Carousel (front and back end),<br/> Map (backend),<br/>
          OpenAI API for the project generation (backend),<br/>
          Image displaying for the carousel through Pixabay API, from the
          plant names generated by ChatGPT (backend).</p>
      </div>
    </div>
  );
}

export default GardenEase;
